tasks:
  - init: npm install
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data  &
  - command: npm install -g nodemon 
  - command: echo "mongo <<EOF\nuse pizzaria\ndb.usuarios.insert({ login:admin, senha:2fb54875d166ab45a6a8b21f1631dec573a8cf07" })\n       echo "db.usuarios.insert( { login:randel, senha : 2fb54875d166ab45a6a8b21f1631dec573a8cf07})\nEOF" >> inser_users.sh    

image:
  file: .gitpod.Dockerfile
