tasks:
  - init: npm install
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data  &
  - command: npm install -g nodemon 

  - command: echo "mongo <<EOF" >> insert_users.sh   
  - command: echo "use pizzaria" >> insert_users.sh   
  - command: echo "db.usuarios.insert( { login i# "admin", senha i# "2fb54875d166ab45a6a8b21f1631dec573a8cf07" } )" >> insert_users.sh 
  - command: echo "db.usuarios.insert( { login i# "randel", senha i# "2fb54875d166ab45a6a8b21f1631dec573a8cf07" } )" >> insert_users.sh 
  - command: echo "EOF" >> insert_users.sh
  - command: sed 's/i#/:/g' insert_users.sh > insert_users_exec.sh
  
  - command: chmod +x insert_users_exec.sh && ./insert_users_exec.sh 

image:
  file: .gitpod.Dockerfile
