tasks:
  - init: npm install
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data  &
  - command: npm install -g nodemon
  - command: mongo <<EOF         
             use pizzaria
             db.usuarios.find({})
             EOF    
image:
  file: .gitpod.Dockerfile
