tasks:
  - init: npm install
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data  &
  - command: npm install -g nodemon 
  - command: sh insert_users_exec.sh
  
image:
  file: .gitpod.Dockerfile
